### ISSUE TITLE
Add TestbedMode dropdown

### ISSUE THREAD

**Issue by thoobr** [DRIVER-EU/test-bed-admin#21]
Add a dropdown to the menubar and display the current testbed mode.
The available testbed modes can be retrieved by HTTP GET: /AdminService/getAllTestbedModes

To select the current active mode you need to call: /AdminService/getActTestbedConfig
In this object the testbedMode propertie is the name of the current mode.
Select this entry in the dropdown

**Comment by croser** [comment]
if it is intended that client posts to setActTestbedConfig upon selection, this should be done. logic is: result for getActTestbedConfig is modified by new mode name; if no result from getActTestbedConfig is available we set configuration to the first available configuration. 

could not be tested in full flow due to a currently empty result of getActTestbedConfig. please review + test + close this ticket if appropriate.

**Comment by thoobr** [comment]
the active configuration is working
